"use client";
import Providers from "@/library/Providers";
import { Inter } from "next/font/google";
import { useState } from "react";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "./globals.css";
import Footer from "./shared/footer/footer";
import Header from "./shared/header/header";
const inter = Inter({ subsets: ["latin"] });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const handleDrawerToggle = () => {
    setSidebarOpen(!sidebarOpen);
  };
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>
          {/* header navbar */}
          <Header
            handleDrawerToggle={handleDrawerToggle}
            sidebarOpen={sidebarOpen}
          />
          {children}
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
