"use client";
import Providers from "@/library/Providers";
import { Drawer } from "@mui/material";
import { Inter } from "next/font/google";
import { useState } from "react";
import "slick-carousel/slick/slick-theme.css";
import "slick-carousel/slick/slick.css";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "../styles/fonts.css";
import "../styles/styles.css";
import "../styles/swiper.css";
import DashboardNav from "./dashboard/components/DashboardNav";
import "./globals.css";
import Footer from "./shared/footer/footer";
import Header from "./shared/header/header";
const inter = Inter({ subsets: ["latin"] });
const myFont = localFont({ src: "../assets/fonts/BR-Omega-Regular.ttf" });
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [sidebarOpen, setSidebarOpen] = useState(false);
  const handleDrawerToggle = () => {
    setSidebarOpen(!sidebarOpen);
  };
  return (
    <Providers>
      <html lang="en">
        <body className={myFont.className}>
          {/* header navbar */}
          <Header
            handleDrawerToggle={handleDrawerToggle}
            sidebarOpen={sidebarOpen}
          />
          {/* Drawer for xs and sm devices */}
          <Drawer
            anchor="left"
            open={sidebarOpen}
            onClose={handleDrawerToggle}
            variant="temporary"
            ModalProps={{
              keepMounted: true,
            }}
            sx={{
              "& .MuiDrawer-paper": {
                width: "295px",
              },
            }}
          >
            <DashboardNav />
          </Drawer>
          {children}
          <Footer />
        </body>
      </html>
    </Providers>
  );
}
function localFont({ src }: { src: string }) {
  // You need to implement this function to load and apply the font
  // Return an object with the necessary properties, including className
  // For now, let's assume it's just applying the font directly to the body
  if (typeof window !== "undefined") {
    document.body.style.fontFamily = `BR-Omega-Regular, sans-serif`;
  }
  return {
    fontFamily: `BR-Omega-Regular, sans-serif`,
    className: "your-font-class-name",
  };
}
